# Generated by Django 3.1 on 2020-09-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('user', '0005_auto_20200925_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_post',
            fields=[
                ('user_post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_type', models.BooleanField()),
                ('title', models.CharField(max_length=264)),
                ('image', models.URLField(blank=True, max_length=264)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=264)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='club_post',
            fields=[
                ('club_post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_type', models.BooleanField()),
                ('title', models.CharField(max_length=264)),
                ('image', models.URLField(blank=True, max_length=264)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=264)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
    ]
