# Generated by Django 3.1 on 2020-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_post',
            name='club_post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='user_post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
