# Generated by Django 3.1 on 2020-09-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200925_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_post',
            name='post_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='post_type',
            field=models.BooleanField(default=False),
        ),
    ]
