# Generated by Django 3.1 on 2020-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200925_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='attachment',
            field=models.FileField(blank=True, upload_to='postextra'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='postmain'),
        ),
    ]
