# Generated by Django 3.1 on 2020-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200930_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='start',
            field=models.DateField(),
        ),
    ]
