# Generated by Django 3.1.1 on 2020-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200930_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_post',
            name='image',
            field=models.URLField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='club_post',
            name='location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='postextra'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postmain'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
