# Generated by Django 3.1.1 on 2020-10-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201003_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_post',
            name='sender_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_post',
            name='sender_type',
            field=models.BooleanField(default=False),
        ),
    ]
