# Generated by Django 3.1.1 on 2020-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201006_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
