# Generated by Django 3.1 on 2020-09-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_auto_20200930_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess_model',
            fields=[
                ('mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('hostel', models.CharField(max_length=264)),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('breakfast2', models.TextField()),
                ('lunch2', models.TextField()),
                ('dinner2', models.TextField()),
                ('contact', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cancel_model',
            fields=[
                ('cancel_id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('mess_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.mess_model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
