# Generated by Django 3.1 on 2020-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_model',
            name='enddate',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancel_model',
            name='startdate',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='breakfast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='breakfast2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='dinner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='dinner2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='lunch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess_model',
            name='lunch2',
            field=models.TextField(blank=True),
        ),
    ]
