# Generated by Django 3.1 on 2020-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20200930_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_model',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='cancel_model',
            name='startdate',
            field=models.DateField(),
        ),
    ]
# default=0.0011494252873563218