# Generated by Django 3.1 on 2020-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20200930_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel_model',
            name='enddate',
            field=models.DateField(default='23/10/2001'),
        ),
        migrations.AlterField(
            model_name='cancel_model',
            name='startdate',
            field=models.DateField(default='23/10/2001'),
        ),
    ]
