# Generated by Django 3.1 on 2020-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_auto_20200930_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_model',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='cancel_model',
            name='startdate',
            field=models.DateField(),
        ),
    ]
# default='23/10/2001'