# Generated by Django 3.1 on 2020-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canteen_model',
            fields=[
                ('canteen_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=264)),
                ('location', models.CharField(blank=True, max_length=264)),
                ('items', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=264)),
            ],
        ),
    ]
