# Generated by Django 3.1.1 on 2020-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen_model',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canteen_model',
            name='location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='canteen_model',
            name='status',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
