# Generated by Django 3.1 on 2020-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20201003_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen_model',
            name='activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteen_model',
            name='authorization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canteen_model',
            name='password',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canteen_model',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
