# Generated by Django 3.1 on 2020-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20201106_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen_model',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
