# Generated by Django 3.1 on 2020-11-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_auto_20201106_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen_model',
            name='phone',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
