# Generated by Django 3.1 on 2020-09-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_auto_20200930_1556'),
        ('club', '0002_auto_20200930_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_user_model',
            fields=[
                ('club_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
