# Generated by Django 3.1 on 2020-09-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('activation', models.BooleanField(default=False)),
                ('role', models.IntegerField(blank=True)),
                ('auth_name', models.CharField(blank=True, max_length=264)),
                ('department', models.CharField(blank=True, max_length=264)),
                ('mess', models.CharField(blank=True, max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='authority',
            fields=[
                ('authority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=264)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
