# Generated by Django 3.1 on 2020-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200925_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='a', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
