# Generated by Django 3.1 on 2020-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200930_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mess',
        ),
        migrations.AddField(
            model_name='user',
            name='mess_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
