# Generated by Django 3.1 on 2020-09-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20200925_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=264)),
                ('council', models.CharField(blank=True, max_length=264)),
                ('email_id', models.CharField(max_length=264)),
                ('profile', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
