# Generated by Django 3.1 on 2020-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email_id',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile',
            field=models.ImageField(blank=True, upload_to='club_pics'),
        ),
    ]
