# Generated by Django 3.1.1 on 2020-10-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201003_1450'),
        ('club', '0002_auto_20200930_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='council',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email_id',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='club_pics'),
        ),
        migrations.AlterField(
            model_name='club',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
